### PR TITLE
Cumulative updates

### PR DESCRIPTION
**Pull request by redtide**
For practice I did a single PR, so it would make sense to use a rebase merge to avoid a single merge commit for all these.
Let me know if I have to change/remove something.

### CODE REVIEW

**Comment by redtide** [comment]
I just made a force push to add the `--window-icon` option to display the app icon in the title bar (not to be confused with info/warning message dialogs' icon).

In [Zenity manual](https://man.archlinux.org/man/zenity.1.en#window-icon=ICONPATH) it's defined to be used on all dialog types, but there is [a bug](https://bugs.launchpad.net/ubuntu/+source/zenity/+bug/998491) so that it doesn't work with `--forms` (and some others):  it doesn't warn or reports an error, just not displayed silently.

However in Qarma it works as expected.

**Comment by stefonarch** [comment]
Thanks,  nice.
Ttitlebar in labwc doesn't  support icons yet.
 There are some things to fix, could be done also afterwards:
* update installing instructions
* change icon also in notifications

**Comment by stefonarch** [comment]
Just tested under wayfire, it doesn't display it, but that's not a big deal.
screen_area_lun_14:26:28_

**Comment by redtide** [comment]
is that zenity? Otherwise it's strange that it shows the generic icon using qarma

**Pull request merged**
